function [f,gof] = lineFit(x,y)
%LINEFIT linear fit of 2-d data
%   Input: 
%      X Input : x
%      Y Output: y
%  Output:
%      f : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
%Edited by Haoyu Wang <whaoyu3@hotmail.com>

%  Auto-generated by MATLAB on 27-Mar-2019 16:30:55


[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1 0];

% Fit model to data.
[f, gof] = fit( xData, yData, ft, opts );

end

